TREE_MAIN = "Derfuu_Nodes"

TREE_VARIABLE = TREE_MAIN + "/Variables"
TREE_TUPLES = TREE_MAIN + "/Tuples"
TREE_MATH = TREE_MAIN + "/Math"
TREE_FUNCTIONS = TREE_MAIN + "/Functions"
TREE_MODDED = TREE_MAIN + "/Modded nodes"

TREE_CONVERTERS = TREE_FUNCTIONS + "/Converters"

TREE_TRIGONOMETRY = TREE_MATH + "/Trigonometry"

TREE_COND = TREE_MODDED + "/Conditions"
TREE_IMAGES = TREE_MODDED + "/Image"
TREE_LATENTS = TREE_MODDED + "/Latent"

TREE_DEBUG = TREE_MAIN + "/Debug"
